### ISSUE TITLE
Some of the templates in {time} dont work

### ISSUE THREAD

**Issue by flamergamer1234** [FelixRilling/ynajs-editor#1]
For example, %B and %b. Here is the full list if you dont know it: https://docs.python.org/3.4/library/datetime.html#strftime-strptime-behavior

**Comment by FelixRilling** [comment]
Hey!

Yeah, that is a know issue; the library YNA.js uses for time formatting works differently than pythons date formatting. I will look for a replacement that supports the same formatting as python.
